### ISSUE TITLE
大佬好像没办法正常下载种子

### ISSUE THREAD

**Issue by 2375399351** [Kanon1982/t66yDownload#1]
可以改成获取磁力链接吗？

**Comment by Kanon1982** [comment]
你下载过程中有没有全程外网模式？
    --因为这个脚本是模拟用户点击，所以需要全程外网环境
你的电脑里是不是安装了迅雷？
    --在脚本下载种子的过程中，需要先卸载迅雷。因为模拟用户点击下载种子的时候，浏览器会外部调用迅雷下载。所以只能先 
       卸载。下载完成之后，再安装。。。

**Comment by Kanon1982** [comment]
我自己用，是可以正常使用的，就是有些慢。
话说，你配置好环境了吗？

**Comment by Kanon1982** [comment]
磁力链接？这两天我改改试试

**Comment by 2375399351** [comment]
> 磁力链接？这两天我改改试试

的确可以，我估计就是迅雷的问题…期待可以自己复制磁力的

**Comment by Kanon1982** [comment]
搞定了。
我试了试，没问题
你试试。。。

**Comment by 2375399351** [comment]
> 搞定了。
> 
> 我试了试，没问题
> 
> 你试试。。。

感谢，可以使用，谢谢作者
